# Directories
ROOT_DIR:
    "/home/yixin/Desktop/github/unimod_pausing"
GEO_PROSEQ_DIR:
    "/data/geo/PROseq"
# Files
HUMAN_CHROMINFO:
    "/home/yixin/evolgen/comparaReg/external_resources/human/chrominfo.txt"
HUMAN_BWA_INDEX:
    "/home/yixin/evolgen/comparaReg/external_resources/human/bwa/index/genome.fasta"
HUMAN_GTF:
    "/home/yixin/evolgen/comparaReg/external_resources/human/transcript.gtf"
HUMAN_NONOLP_GENE:
    "/home/yixin/evolgen/comparaReg/external_resources/human/non_overlapping_coding_genes.csv"

# Parameters
tss_length: 250 # parameter k
tts_length: 250 # parameter m
rc_cutoff: 10 # cutoff for PRO-cap 5' end read count to be considered as active
        