#!/usr/bin/env python3
"""
check_paths.py — validate that required data files are present.

Required files (bundled with the package) cause an error if missing.
Optional large files (reference genomes, BAMs, BigWigs) print warnings only.

Usage:
  python codes/publish/check_paths.py
  PROJECT_ROOT=/other/path python codes/publish/check_paths.py
"""

import os
import sys
from pathlib import Path

_PUBLISH_DIR = Path(__file__).resolve().parent   # codes/publish/
_DEFAULT_ROOT = _PUBLISH_DIR.parent       # project root

PROJECT_ROOT = Path(os.path.expanduser(
    os.environ.get("PROJECT_ROOT", str(_DEFAULT_ROOT))
)).resolve()

DATA_ROOT   = PROJECT_ROOT / "data" / "publish"
ENCODE_BAM  = Path(os.environ.get("ENCODE_BAM_ROOT",  str(PROJECT_ROOT / "data" / "result2" / "encode" / "bam")))
ENCODE_BW   = Path(os.environ.get("ENCODE_BW_ROOT",   str(PROJECT_ROOT / "data" / "result2" / "encode" / "bw_clean")))
GENOME_ROOT = Path(os.environ.get("GENOME_ROOT",      str(PROJECT_ROOT / "codes" / "micro-c")))
MICROC_1D   = Path(os.environ.get("MICROC_1D_ROOT",   str(PROJECT_ROOT / "data" / "micro-c")))

REQUIRED: list[Path] = [
    _PUBLISH_DIR / "paths.yaml",
    _PUBLISH_DIR / "load_config.R",
    _PUBLISH_DIR / "paths.sh",
    DATA_ROOT / "proseq/tidgrng/PROseq-HUMAN-CD4_tsn.RDS",
    DATA_ROOT / "proseq/tidgrng/PROseq-HUMAN-CD14_tsn.RDS",
    DATA_ROOT / "proseq/tidgrng/PROseq-RHESUS-CD4_tsn.RDS",
    DATA_ROOT / "proseq/tidgrng/PROseq-RHESUS-CD14_tsn.RDS",
    DATA_ROOT / "proseq/tidgrng/PROseq-BABOON-CD4_tsn.RDS",
    DATA_ROOT / "proseq/tidgrng/PROseq-BABOON-CD14_tsn.RDS",
    DATA_ROOT / "proseq/tq/HUMAN.RDS",
    DATA_ROOT / "proseq/tq/RHESUS.RDS",
    DATA_ROOT / "proseq/tq/BABOON.RDS",
    DATA_ROOT / "proseq/bigwig/p3/PROseq-HUMAN-CD4_plus.bw",
    DATA_ROOT / "proseq/bigwig/p3/PROseq-HUMAN-CD4_minus.bw",
    DATA_ROOT / "proseq/bigwig/p3/PROseq-HUMAN-CD14_plus.bw",
    DATA_ROOT / "proseq/bigwig/p3/PROseq-HUMAN-CD14_minus.bw",
    DATA_ROOT / "proseq/bigwig/p3/PROseq-RHESUS-CD4_plus.bw",
    DATA_ROOT / "proseq/bigwig/p3/PROseq-RHESUS-CD4_minus.bw",
    DATA_ROOT / "proseq/bigwig/p3/PROseq-RHESUS-CD14_plus.bw",
    DATA_ROOT / "proseq/bigwig/p3/PROseq-RHESUS-CD14_minus.bw",
    DATA_ROOT / "proseq/bigwig/p3/PROseq-BABOON-CD4_plus.bw",
    DATA_ROOT / "proseq/bigwig/p3/PROseq-BABOON-CD4_minus.bw",
    DATA_ROOT / "proseq/bigwig/p3/PROseq-BABOON-CD14_plus.bw",
    DATA_ROOT / "proseq/bigwig/p3/PROseq-BABOON-CD14_minus.bw",
    DATA_ROOT / "encode/peaks/ENCFF880RNP.bed",
    DATA_ROOT / "encode/peaks/ENCFF993CWV.bed",
    DATA_ROOT / "encode/peaks/ENCFF353RHA.bed",
    DATA_ROOT / "encode/peaks/ENCFF780UIQ.bed",
    DATA_ROOT / "encode/peaks/ENCFF472QFJ.bed",
    DATA_ROOT / "encode/peaks/ENCFF634HCJ.bed",
    DATA_ROOT / "encode/peaks/ENCFF465ZYQ.bed",
    DATA_ROOT / "encode/peaks/ENCFF506FIB.bed",
    DATA_ROOT / "encode/metadata/meta_bam.RDS",
    DATA_ROOT / "encode/metadata/meta_fc.RDS",
    DATA_ROOT / "dreg/PROseq-HUMAN-CD4.dREG.peak.prob.bed",
    DATA_ROOT / "dreg/PROseq-HUMAN-CD14.dREG.peak.prob.bed",
    DATA_ROOT / "liftover/hglft_genome_3a4e45_25bea0.bed",
    DATA_ROOT / "liftover/hglft_genome_36cd63_262e10.bed",
    DATA_ROOT / "liftover/hglft_genome_4ecd_9138e0.bed",
    DATA_ROOT / "liftover/hglft_genome_3ff64c_9134c0.bed",
    DATA_ROOT / "orthology/human__v__baboon.tsv",
    DATA_ROOT / "orthology/human__v__rhesus.tsv",
    DATA_ROOT / "promoter_annotation/merge_promoter_motif.txt",
    DATA_ROOT / "ep_contacts/cd4_EP_and_BG_contacts.txt",
    DATA_ROOT / "ep_contacts/cd14_EP_and_BG_contacts.txt",
]

OPTIONAL_LARGE: list[tuple[Path, str]] = [
    (GENOME_ROOT / "hg38.fa",    "hg38 reference genome — download from UCSC (hg38.fa.gz)"),
    (GENOME_ROOT / "papAnu4.fa", "Baboon reference genome — download from UCSC (papAnu4.fa.gz)"),
    (GENOME_ROOT / "rheMac10.fa","Rhesus reference genome — download from UCSC (rheMac10.fa.gz)"),
    (ENCODE_BAM,  "ENCODE ChIP-seq BAM directory — see encode/encode_bam_metadata.csv"),
    (ENCODE_BW,   "ENCODE fold-change BigWig directory — see encode/encode_bigwig_metadata.csv"),
    (MICROC_1D,   "Micro-C 1D signal BED directory — generated by singleCellType/2_1_3_batch_extract_1d_signal.sh"),
]


def main() -> None:
    print(f"PROJECT_ROOT : {PROJECT_ROOT}")
    print(f"DATA         : {DATA_ROOT}")
    print()

    missing = [p for p in REQUIRED if not p.exists()]
    if missing:
        print(f"REQUIRED [{len(REQUIRED) - len(missing)}/{len(REQUIRED)} present] — missing:")
        for p in missing:
            print(f"  [MISSING]  {p.relative_to(PROJECT_ROOT)}")
    else:
        print(f"REQUIRED ({len(REQUIRED)} files): all present")

    print()
    print("OPTIONAL_LARGE (warnings only):")
    warned = 0
    for path, desc in OPTIONAL_LARGE:
        if not path.exists():
            try:
                rel = path.relative_to(PROJECT_ROOT)
            except ValueError:
                rel = path
            print(f"  [WARN]  {rel}")
            print(f"          {desc}")
            warned += 1
    if warned == 0:
        print("  all optional paths present")

    print()
    if missing:
        print(f"FAIL — {len(missing)} required file(s) missing.")
        sys.exit(1)
    else:
        print("OK — all required paths present.")


if __name__ == "__main__":
    main()
